### ISSUE TITLE
Crash on startup "Fermenter Resource item cannot be empty!"

### ISSUE THREAD

**Issue by carstorm** [the-realest-stu/Rustic#82]
[crash-2017-09-13_01.42.05-client.txt](https://github.com/the-realest-stu/Rustic/files/1298440/crash-2017-09-13_01.42.05-client.txt)

**Comment by the-realest-stu** [comment]
I released an update yesterday which fixes that. Check curseforge for updates before reporting issues.

**Comment by carstorm** [comment]
I did update. If 0.4.1 isn't the latest version blame the twitch client for still not showing the update!

**Comment by carstorm** [comment]
Found the issue and why twitch wasn't showing the updated file. Anything after 0.4.1 is only for MC 1.12.1 rather than both. Is that by necessity or oversight?

**Comment by the-realest-stu** [comment]
Sorry, didn't mean to come off as condescending or rude. 0.4.3 _might_ work on 1.12.0, even though it isn't listed, so I can try that out and list it if it is. Otherwise, you should probably be able to update to 1.12.1 because 99% of mods that worked on 1.12.0 still work on 1.12.1, even if 1.12.1 isn't listed as compatible. Pretty much all mods that didn't work on 1.12.1 already have been updated by now. I know the Twitch client is weird about versions, but that's kinda on them, and it's something everyone using their launcher has to deal with.

**Comment by the-realest-stu** [comment]
Okay, I just tried it out, and the Rustic 0.4.3 doesn't work on 1.12.0.
One solution that I totally forgot about before, though, is that you can simply downgrade Forestry to version 1.12.1-5.5.4.187, and that should work just fine. You wouldn't lose anything from Forestry or anything.
If you don't want to do that for some reason, try updating to 1.12.1, and let me know if there are any mods that haven't updated, and if so, which mods in particular. If I can't find working versions of those mods for 1.12.1, I'll backport this latest update to 1.12.0. But I really don't expect it to come to that.

**Comment by carstorm** [comment]
Just tried to downgrade forestry as suggested, didn't work.

[crash-2017-09-14_15.15.55-client.txt](https://github.com/the-realest-stu/Rustic/files/1304427/crash-2017-09-14_15.15.55-client.txt)

**Comment by the-realest-stu** [comment]
Well, according to that crash log, you're on 1.12.1 now, so updating Rustic should now be possible. It's odd that downgrading Forestry didn't work, I was told that it did.

**Comment by carstorm** [comment]
That crashlog does have the latest version of rustic, its still crashes naming Rustic as the issue.

**Comment by the-realest-stu** [comment]
In the 1.12.1 instance you need to update forestry. It seems as though you both downgraded forestry and updated Rustic at the same time, but that breaks things. I meant that you should only do one or the other, not both.

**Comment by carstorm** [comment]
Ahh at one point I did but then reverted due to the pack not crashing immediately with no report. However I just updated all mods that had an update and the pack now starts on 1.12.1. TY

**Comment by Morpheus1101** [comment]
Im using 1.12.2 and em now getting this exact same error https://puu.sh/xLJLp/6021f12aa5.txt

Forge *.2493
Rustic v0.4.1
Forestry v5.5.6.197

**Comment by the-realest-stu** [comment]
Update to Rustic 0.4.3 (It's been out for over 2 weeks now). I'll tag it as 1.12.2 on curseforge, because I'm hoping that's why you haven't updated. If you're using the twitch launcher, it only shows you mods that are specifically labeled for the version you're using, which in 1.12.X tends to be very misleading, since most mods that work in 1.12.0 also work in 1.12.1 and 1.12.2.

**Comment by Morpheus1101** [comment]
Yes, that is literally the only reason why, admittedly i do tend to check that, teach me for being lazy lol
